version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sead_backend
    expose:
      - "5151"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sead_frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped