version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sead_backend
    ports:
      - "5151:5151"
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sead_frontend
    expose:
      - "80"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge