"""quilometragem

Revision ID: 534e5d52ccbe
Revises: 262cd6c16d2a
Create Date: 2025-08-18 19:18:30.400822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534e5d52ccbe'
down_revision: Union[str, Sequence[str], None] = '262cd6c16d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veiculo', sa.Column('quilometragem', sa.Integer(), nullable=False, server_default='0'))
    # Remova o default se quiser, após a migração:
    op.alter_column('veiculo', 'quilometragem', server_default=None)
    op.drop_column('veiculo', 'kilometragem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veiculo', sa.Column('kilometragem', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('veiculo', 'quilometragem')
    # ### end Alembic commands ###
