"""initial migration

Revision ID: 5ea5930a6963
Revises: 
Create Date: 2025-08-04 17:16:47.609746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add this import


# revision identifiers, used by Alembic.
revision: str = '5ea5930a6963'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('evento', sa.Column('nome_solicitante', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    
    # Update existing records with a default value
    op.execute("UPDATE evento SET nome_solicitante = 'N/A' WHERE nome_solicitante IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('evento', 'nome_solicitante', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'nome_solicitante')
    # ### end Alembic commands ###
