"""Status de aprovação

Revision ID: 9b9a4298eb82
Revises: 534e5d52ccbe
Create Date: 2025-08-22 17:14:53.855296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9a4298eb82'
down_revision: Union[str, Sequence[str], None] = '534e5d52ccbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with default value for existing rows
    op.add_column('evento', sa.Column('aprovado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Remove server_default after creation (optional, for future inserts)
    op.alter_column('evento', 'aprovado', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'aprovado')
    # ### end Alembic commands ###
